// Single surface→semantic→canonical map (Phase 6F T03).
// Closed set: fixture-gated growth only. Unknown phrases return null.
// Surface vocabulary never decides skill ownership (no skill names here).

const ENTRIES = {
  // understanding / discovery verbs
  map: ['understanding', 'understand'],
  analyze: ['understanding', 'understand'],
  explain: ['understanding', 'understand'],
  explore: ['understanding', 'understand'],
  // inspect maps to verification/review (examine/verify), not understanding
  inspect: ['verification', 'review'],
  // "inspect the build artifact" is a quality/readiness check → verification/assess
  'inspect-build-artifact': ['verification', 'assess'],
  'inspect-the-build-artifact': ['verification', 'assess'],
  survey: ['understanding', 'understand'],
  learn: ['understanding', 'understand'],
  look: ['understanding', 'understand'],

  // requirements / definition verbs
  define: ['requirements', 'define'],
  specify: ['requirements', 'define'],
  clarify: ['requirements', 'define'],
  gather: ['requirements', 'define'],
  capture: ['requirements', 'define'],
  known: ['requirements', 'define'],
  unknown: ['requirements', 'define'],

  // planning verbs
  plan: ['planning', 'plan'],
  prepare: ['planning', 'plan'],
  scope: ['planning', 'plan'],
  strategy: ['planning', 'plan'],
  roadmap: ['planning', 'plan'],
  approach: ['planning', 'plan'],
  estimate: ['planning', 'plan'],
  breakdown: ['planning', 'plan'],

  // design verbs
  design: ['design', 'design'],
  layout: ['design', 'design'],
  mockup: ['design', 'design'],
  wireframe: ['design', 'design'],
  prototype: ['design', 'design'],
  redesign: ['design', 'design'],

  // implementation verbs
  implement: ['implementation', 'implement'],
  build: ['implementation', 'implement'],
  create: ['implementation', 'implement'],
  add: ['implementation', 'implement'],
  develop: ['implementation', 'implement'],
  write: ['implementation', 'implement'],
  modify: ['implementation', 'implement'],
  update: ['implementation', 'implement'],
  refactor: ['implementation', 'implement'],

  // fix/repair verbs
  fix: ['implementation', 'fix'],
  repair: ['implementation', 'fix'],
  patch: ['implementation', 'fix'],
  resolve: ['implementation', 'fix'],
  correct: ['implementation', 'fix'],
  'fix-bug': ['implementation', 'fix'],
  'fix-issue': ['implementation', 'fix'],
  'fix-error': ['implementation', 'fix'],
  'fix-crash': ['implementation', 'fix'],
  'fix-leak': ['implementation', 'fix'],
  'fix-null': ['implementation', 'fix'],
  'fix-token': ['implementation', 'fix'],
  'fix-login': ['implementation', 'fix'],
  'fix-auth': ['implementation', 'fix'],
  'fix-mapper': ['implementation', 'fix'],

  // investigation/diagnosis verbs
  investigate: ['diagnosis', 'investigate'],
  debug: ['diagnosis', 'investigate'],
  diagnose: ['diagnosis', 'investigate'],
  troubleshoot: ['diagnosis', 'investigate'],
  find: ['diagnosis', 'investigate'],
  determine: ['diagnosis', 'investigate'],
  identify: ['diagnosis', 'investigate'],
  trace: ['understanding', 'understand'],
  'root-cause': ['diagnosis', 'investigate'],
  'root cause': ['diagnosis', 'investigate'],
  'figure-out': ['diagnosis', 'investigate'],
  'work-out': ['diagnosis', 'investigate'],
  'determine-why': ['diagnosis', 'investigate'],
  'work-out-what': ['diagnosis', 'investigate'],
  'root-cause': ['diagnosis', 'investigate'],

  // testing/verification verbs
  test: ['testing', 'test'],
  tests: ['testing', 'test'],
  'regression-test': ['testing', 'test'],
  'regression-tests': ['testing', 'test'],
  verify: ['testing', 'test'],
  validate: ['verification', 'test'],
  confirm: ['delivery', 'assess'],
  rerun: ['testing', 'test'],
  run: ['testing', 'test'],

  // review/audit verbs
  review: ['verification', 'review'],
  audit: ['assessment', 'assess'],
  evaluate: ['verification', 'review'],
  'threat-model': ['assessment', 'assess'],

  // upgrade/migration verbs
  upgrade: ['implementation', 'upgrade'],
  migrate: ['implementation', 'upgrade'],

  // assessment verbs
  assess: ['assessment', 'assess'],
  check: ['verification', 'assess'],

  // deployment verbs
  deploy: ['deployment', 'deploy'],
  promote: ['deployment', 'deploy'],
  rollout: ['deployment', 'deploy'],
  publish: ['delivery', 'deploy'],

  // recovery verbs
  recover: ['recovery', 'recover'],
  reconstruct: ['recovery', 'recover'],
  resume: ['recovery', 'recover'],

  // git verbs
  commit: ['git-op', 'git'],
  rebase: ['git-op', 'git'],
  push: ['git-op', 'git'],
  merge: ['git-op', 'git'],
  branch: ['git-op', 'git'],
  stage: ['git-op', 'git'],
  'cherry-pick': ['git-op', 'git'],

  // testing aliases (specific contexts only - generic run handled by target)
  'run-test': ['testing', 'test'],
  'run-tests': ['testing', 'test'],
  'run-suite': ['testing', 'test'],
  'run-integration': ['testing', 'test'],
  'run-unit': ['testing', 'test'],
  'run-e2e': ['testing', 'test'],
  'run-contract': ['testing', 'test'],
  'run-regression': ['testing', 'test'],
  execute: ['testing', 'test'],
  'test-suite': ['testing', 'test'],
  'test suite': ['testing', 'test'],
  'smoke-suite': ['testing', 'test'],
  'smoke-test': ['testing', 'test'],
  'smoke-tests': ['testing', 'test'],
  // deployment operations
  'run-server': ['deployment', 'deploy'],
  'run-staging': ['deployment', 'deploy'],
  'run-production': ['deployment', 'deploy'],
  'run-prod': ['deployment', 'deploy'],
  'run-app': ['deployment', 'deploy'],
  'run-application': ['deployment', 'deploy'],
  'run-service': ['deployment', 'deploy'],
  'run-container': ['deployment', 'deploy'],
  'run-pipeline': ['deployment', 'deploy'],
  'run-ci': ['deployment', 'deploy'],
  'run-build': ['deployment', 'deploy'],
  'run-migration': ['deployment', 'deploy'],
  // validation/assessment
  'validate-migration': ['verification', 'assess'],
  'validate-data-migration': ['verification', 'assess'],
  'validate-data': ['verification', 'assess'],
  'validate-deployment': ['verification', 'assess'],
  'validate-config': ['verification', 'assess'],
  'validate-schema': ['verification', 'assess'],
  'migration-validation': ['verification', 'assess'],
  'migration-validate': ['verification', 'assess'],
  // migration operations
  migration: ['implementation', 'upgrade'],
  'data-migration': ['implementation', 'upgrade'],

  // multi-word / colloquial (hyphenated for n-gram matching)
  'look-at': ['understanding', 'understand'],
  'can-you-look-at': ['understanding', 'understand'],
  'check-whether': ['delivery', 'assess'],
  'assess-whether': ['delivery', 'assess'],
  'ready-to': ['delivery', 'assess'],
  'ready-to-release': ['delivery', 'assess'],
  'release-readiness': ['delivery', 'assess'],
  'find-release': ['delivery', 'assess'],
  'find-the': ['delivery', 'assess'],
  'find-release-notes': ['delivery', 'assess'],
  release: ['delivery', 'release'],
  ship: ['delivery', 'release'],
  publish: ['delivery', 'release'],
  'ready-to-publish': ['delivery', 'assess'],
  'confirm-release': ['delivery', 'release'],
  handoff: ['delivery', 'release'],
  deliver: ['delivery', 'release'],
  'check-readiness': ['delivery', 'assess'],
  'assess-readiness': ['delivery', 'assess'],
  'evaluate-release': ['delivery', 'assess'],
  'push-to-production': ['operations', 'deploy'],
  'deploy-to-prod': ['operations', 'deploy'],
  'deploy-production': ['operations', 'deploy'],
  'push-to-staging': ['operations', 'deploy'],
  'stage-deploy': ['operations', 'deploy'],
  rollback: ['operations', 'deploy'],
  'rollback-migration': ['planning', 'plan'],
  'prepare-deployment': ['planning', 'plan'],
  'deployment-steps': ['planning', 'plan'],
  'deployment-config': ['planning', 'plan'],
  'deployment-configuration': ['planning', 'plan'],
  'prepare-rollback': ['planning', 'plan'],
  'ci': ['operations', 'deploy'],
  'cd': ['operations', 'deploy'],
  pipeline: ['operations', 'deploy'],
  container: ['operations', 'deploy'],
  docker: ['operations', 'deploy'],
  kubernetes: ['operations', 'deploy'],
  environment: ['operations', 'deploy'],
  infrastructure: ['operations', 'deploy'],
  canary: ['operations', 'deploy'],
  monitor: ['operations', 'deploy'],
  observability: ['operations', 'deploy'],
  'threat-model': ['assessment', 'assess'],
  'security-audit': ['assessment', 'assess'],
  'audit-security': ['assessment', 'assess'],
  'penetration-test': ['assessment', 'assess'],
  pentest: ['assessment', 'assess'],
  'security-review': ['verification', 'review'],
  'code-review': ['verification', 'review'],
  'pr-review': ['verification', 'review'],
  'security-assessment': ['assessment', 'assess'],
  'threat-modeling': ['assessment', 'assess'],
  'migration-plan': ['planning', 'plan'],
  'rollout-plan': ['planning', 'plan'],
  'push-to': ['operations', 'deploy'],
  'roll-out': ['operations', 'deploy'],
  rollout: ['deployment', 'deploy'],
  'merge-locally': ['git-op', 'git'],
  'merge-feature-branch': ['git-op', 'git'],
  'upgrade-dependency': ['implementation', 'upgrade'],
  'framework-upgrade': ['implementation', 'upgrade'],
  'update-dependency': ['implementation', 'upgrade'],
  'regression-test': ['testing', 'test'],
  'regression-tests': ['testing', 'test'],
  'write-test': ['implementation', 'implement'],
  'add-test': ['implementation', 'implement'],
  'create-test': ['implementation', 'implement'],
  'automated-test': ['testing', 'test'],
  'unit-test': ['testing', 'test'],
  'unit-tests': ['testing', 'test'],
  'integration-test': ['testing', 'test'],
  'integration-tests': ['testing', 'test'],
  'e2e-test': ['testing', 'test'],
  'test-suite': ['testing', 'test'],
  'add-tests': ['testing', 'test'],
  'write-tests': ['testing', 'test'],
  'create-tests': ['testing', 'test'],
  'add-regression-tests': ['testing', 'test'],
  'write-regression-tests': ['testing', 'test'],
  'create-regression-tests': ['testing', 'test'],
  'add-unit-coverage': ['testing', 'test'],
  'write-integration-tests': ['testing', 'test'],
  'write-unit-tests': ['testing', 'test'],
  'create-unit-tests': ['testing', 'test'],
  'add-integration-tests': ['testing', 'test'],
  'create-integration-tests': ['testing', 'test'],
  'security-audit-logging': ['assessment', 'assess'],
  'security-audit': ['assessment', 'assess'],
  'security-review': ['verification', 'review'],
  'add-security': ['implementation', 'implement'],
  'fix-bug': ['implementation', 'fix'],
  'fix-issue': ['implementation', 'fix'],
  'fix-error': ['implementation', 'fix'],
  'fix-crash': ['implementation', 'fix'],
  'fix-leak': ['implementation', 'fix'],
  'fix-null': ['implementation', 'fix'],
  'fix-token': ['implementation', 'fix'],
  'fix-login': ['implementation', 'fix'],
  'fix-auth': ['implementation', 'fix'],
  'fix-mapper': ['implementation', 'fix'],
  'resolve-conflicts': ['implementation', 'fix'],
  'resolve-merge-conflicts': ['implementation', 'fix'],
  'resolve-the-merge-conflicts': ['implementation', 'fix'],
  'implement-feature': ['implementation', 'implement'],
  'implement-api': ['implementation', 'implement'],
  'implement-endpoint': ['implementation', 'implement'],
  'build-feature': ['implementation', 'implement'],
  'build-api': ['implementation', 'implement'],
  'build-endpoint': ['implementation', 'implement'],
  'find-root-cause': ['diagnosis', 'investigate'],
  'find-cause': ['diagnosis', 'investigate'],
  'determine-cause': ['diagnosis', 'investigate'],
  'what-caused': ['diagnosis', 'investigate'],
  'what-is-causing': ['diagnosis', 'investigate'],
  'trace-what-is-causing': ['diagnosis', 'investigate'],
  'trace-what-causing': ['diagnosis', 'investigate'],
  'why-did': ['diagnosis', 'investigate'],
  'why-does': ['diagnosis', 'investigate'],
  'why-is': ['diagnosis', 'investigate'],
  'recover-implementation': ['recovery', 'recover'],
  'resume-implementation': ['recovery', 'recover'],
  'interrupted-implementation': ['recovery', 'recover'],
  'lost-context': ['recovery', 'recover'],
  'where-was-i': ['recovery', 'recover'],
  'replay-implementation': ['recovery', 'recover'],
  'commit-completed': ['git-op', 'git'],
  'commit-only': ['git-op', 'git'],
  'completed-task-files': ['git-op', 'git'],
  'commit-locally': ['git-op', 'git'],
  'commit-local': ['git-op', 'git'],
  'no-push': ['git-op', 'git'],
  'dont-push': ['git-op', 'git'],
  'do-not-push': ['git-op', 'git'],
  'without-push': ['git-op', 'git'],
  'merge-branch': ['git-op', 'git'],
  'merge-feature': ['git-op', 'git'],
  'merge-develop': ['git-op', 'git'],
  'merge-main': ['git-op', 'git'],
  'merge-master': ['git-op', 'git'],
  'feature-branch': ['git-op', 'git'],
  'create-branch': ['git-op', 'git'],
  'switch-branch': ['git-op', 'git'],
  'checkout-branch': ['git-op', 'git'],
  'plan-migration': ['planning', 'plan'],
  'plan-rollout': ['planning', 'plan'],
  'plan-rollback': ['planning', 'plan'],
  'migration-plan': ['planning', 'plan'],
  'rollback-plan': ['planning', 'plan'],
  'plan-only': ['planning', 'plan'],
  'planning-only': ['planning', 'plan'],
  'prepare-only': ['planning', 'plan'],
  'steps-only': ['planning', 'plan'],
  'without-deploy': ['planning', 'plan'],
  'without-implementing': ['planning', 'plan'],
  'without-implement': ['planning', 'plan'],
  'do-not-deploy': ['planning', 'plan'],
  'do-not-implement': ['planning', 'plan'],
  'dont-deploy': ['planning', 'plan'],
  'dont-implement': ['planning', 'plan'],
  'no-deploy': ['planning', 'plan'],
  'no-implement': ['planning', 'plan'],
  'qa-matrix': ['verification', 'assess'],
  'regression-matrix': ['verification', 'assess'],
  'quality-matrix': ['verification', 'assess'],
  'risk-matrix': ['verification', 'assess'],
  'scenario-matrix': ['verification', 'assess'],
  'coverage-matrix': ['verification', 'assess'],
  'qa-regression-matrix': ['verification', 'assess'],
  'create-matrix': ['verification', 'assess'],
  'write-matrix': ['verification', 'assess'],
  'build-matrix': ['verification', 'assess'],
  'security-audit': ['assessment', 'assess'],
  'audit-security': ['assessment', 'assess'],
  'security-review': ['verification', 'review'],
  'review-security': ['verification', 'review'],
  'vulnerability-review': ['verification', 'review'],
  'vulnerability-audit': ['assessment', 'assess'],
  'threat-model': ['assessment', 'assess'],
  'threat-model': ['assessment', 'assess'],
  oauth: ['implementation', 'implement'],
  'oauth-login': ['implementation', 'implement'],
  'oauth-implementation': ['implementation', 'implement'],
  'authorization-flow': ['implementation', 'implement'],
  'acceptance-criteria': ['implementation', 'implement'],
  'approved-criteria': ['implementation', 'implement'],
  'implement-oauth': ['implementation', 'implement'],
  'build-oauth': ['implementation', 'implement'],
  'add-oauth': ['implementation', 'implement'],
  'auth-vulnerabilities': ['verification', 'review'],
  'authorization-vulnerabilities': ['verification', 'review'],
  'auth-diff': ['verification', 'review'],
  'review-auth': ['verification', 'review'],
  'review-code': ['verification', 'review'],
  'review-pr': ['verification', 'review'],
  'review-changes': ['verification', 'review'],
  'review-implementation': ['verification', 'review'],
  'review-design': ['verification', 'review'],
  'review-architecture': ['verification', 'review'],
  'review-for': ['verification', 'review'],
  'review-only': ['verification', 'review'],
  'only-review': ['verification', 'review'],
  'do-not-change': ['verification', 'review'],
  'dont-change': ['verification', 'review'],
  'no-changes': ['verification', 'review'],
  'without-changes': ['verification', 'review'],
  'no-modifications': ['verification', 'review'],
  'without-modifications': ['verification', 'review'],
  correctness: ['verification', 'review'],
  maintainability: ['verification', 'review'],
  'known-null': ['implementation', 'fix'],
  'null-token': ['implementation', 'fix'],
  'known-cause': ['implementation', 'fix'],
  'root-cause-confirmed': ['implementation', 'fix'],
  'fix-known': ['implementation', 'fix'],
  'fix-login': ['implementation', 'fix'],
  'fix-auth': ['implementation', 'fix'],
  'fix-mapper': ['implementation', 'fix'],
  'fix-token': ['implementation', 'fix'],
  'unknown-cause': ['diagnosis', 'investigate'],
  'unknown-reason': ['diagnosis', 'investigate'],
  'cause-unknown': ['diagnosis', 'investigate'],
  'reason-unknown': ['diagnosis', 'investigate'],
  'unclear-why': ['diagnosis', 'investigate'],
  'not-sure-why': ['diagnosis', 'investigate'],
  mystery: ['diagnosis', 'investigate'],
  'unknown-origin': ['diagnosis', 'investigate'],
  intermittent: ['diagnosis', 'investigate'],
  flaky: ['diagnosis', 'investigate'],
  'no-confirmed-cause': ['diagnosis', 'investigate'],
  'intermittent-ci': ['diagnosis', 'investigate'],
  'ci-failure': ['diagnosis', 'investigate'],
  'ci-pipeline-failure': ['diagnosis', 'investigate'],
  'build-failure': ['diagnosis', 'investigate'],
  'pipeline-failure': ['diagnosis', 'investigate'],
  'memory-leak': ['diagnosis', 'investigate'],
  'connection-refused': ['diagnosis', 'investigate'],
  timeout: ['diagnosis', 'investigate'],
  'network-error': ['diagnosis', 'investigate'],
  'out-of-memory': ['diagnosis', 'investigate'],
  oom: ['diagnosis', 'investigate'],
  'segmentation-fault': ['diagnosis', 'investigate'],
  crash: ['diagnosis', 'investigate'],
  error: ['diagnosis', 'investigate'],
  bug: ['diagnosis', 'investigate'],
  issue: ['diagnosis', 'investigate'],
  problem: ['diagnosis', 'investigate'],
  incident: ['diagnosis', 'investigate'],
  outage: ['diagnosis', 'investigate'],
  downtime: ['diagnosis', 'investigate'],
  broken: ['diagnosis', 'investigate'],
  failing: ['diagnosis', 'investigate'],
  failed: ['diagnosis', 'investigate'],
};

const table = Object.create(null);
for (const [verb, [semanticCapability, canonicalAction]] of Object.entries(ENTRIES)) {
  table[verb] = Object.freeze({ semanticCapability, canonicalAction });
}

export const SURFACE_TO_CAPABILITY = Object.freeze(table);

export function lookupSurfaceOperation(phrase) {
  if (typeof phrase !== 'string') return null;
  let surfaceVerb = phrase.trim().toLowerCase();
  // Normalize spaces to hyphens for surface map lookup
  surfaceVerb = surfaceVerb.replace(/\s+/g, '-');
  const entry = SURFACE_TO_CAPABILITY[surfaceVerb];
  if (!entry) return null;
  return { surfaceVerb: phrase.trim().toLowerCase(), semanticCapability: entry.semanticCapability, canonicalAction: entry.canonicalAction };
}
